services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      # Frontend port
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=Europe/Moscow
